

const IMAGES = {
  logo: '/logo.svg',
  favicon: '/favicon.svg',
  camera: '/camera.svg',
  user: '/User.svg',
  shoppingCart: '/ShoppingCart.svg',
  cart: '/ShoppingCart.svg',
  chartBar: '/ChartBar.svg',
  envelope: '/Envelope.svg',
  facebook: '/facebook.svg',
  instagram: '/instagram.svg',
  mapPin: '/MapPin.svg',
  megaphone: '/Megaphone.svg',
  notepad: '/Notepad.svg',
  phone: '/Phone.svg',
  profile: '/profile.svg',
  sasha: '/Sasha.svg',
  sealCheck: '/SealCheck.svg',
  shieldCheck: '/ShieldCheck.svg',
  shop: '/shop.svg',
  shoppingBag: '/shoppingBag.svg',
  shoppingCartSimple: '/ShoppingCartSimple.svg',
  star: '/star.svg',
  storeCover: '/storeCover.svg',
  whatsapp: '/whatsapp.svg',
  x: '/X.svg',
  login: '/login.svg',
  Xcircle: '/XCircle.svg',
  backarrow: '/backarrow.svg',
  storeCoverSmall: '/storeCoverSmall.svg',
  laptop: '/laptop.svg',
  laptop2: '/laptop2.svg  ',
  cutBg: '/cut-bg.svg',
  shopping_Cart: '/shopping-cart.svg',
  image : '/Image.svg',
  caretLeft: '/CaretLeft.svg',
  DownloadSimple: '/DownloadSimple.svg',
  pencil: '/Pencil.svg',
  DotsThree: '/DotsThree.svg',
  iphone: '/iphone.jpg',
  top1: '/top1.jpg',
  top2: '/top2.jpg',
  top3: '/top3.jpg',
  top4: '/top4.jpg',
  PencilSimpleLine: '/PencilSimpleLine.svg',
  DotsThreeOutlineVertical: '/DotsThreeOutlineVertical.svg',
  fire: '/Fire.svg',
  feedPhone: '/FeedPhone.svg',
   vee: '/Vee.png',
    adam: '/adams.svg',
    download: '/download.svg'
};

export default IMAGES;
